export const GET_MY_BOOKINGS_PENDING = 'bookingHistory/GET_MY_BOOKINGS_PENDING';
export const GET_MY_BOOKINGS_SUCCESS = 'bookingHistory/GET_MY_BOOKINGS_SUCCESS';
export const GET_MY_BOOKINGS_FAILURE = 'bookingHistory/GET_MY_BOOKINGS_FAILURE';

export const GET_BOOKING_DETAILS_PENDING = 'bookingHistory/GET_BOOKING_DETAILS_PENDING';
export const GET_BOOKING_DETAILS_SUCCESS = 'bookingHistory/GET_BOOKING_DETAILS_SUCCESS';
export const GET_BOOKING_DETAILS_FAILURE = 'bookingHistory/GET_BOOKING_DETAILS_FAILURE';

export const CANCEL_BOOKING_PENDING = 'bookingHistory/CANCEL_BOOKING_PENDING';
export const CANCEL_BOOKING_SUCCESS = 'bookingHistory/CANCEL_BOOKING_SUCCESS';
export const CANCEL_BOOKING_FAILURE = 'bookingHistory/CANCEL_BOOKING_FAILURE';

export const CLEAR_SELECTED_BOOKING = 'bookingHistory/CLEAR_SELECTED_BOOKING';
