const SAVE_BUS_TIMES = 'bus/SAVE_BUS_TIMES'
const NO_BUS_TIMES = 'bus/NO_BUS_TIMES'
const APPLY_SORTING = 'bus/APPLY_SORTING'
const CHANGE_SELECTED_FILTER = 'bus/CHANGE_SELECTED_FILTER'
const CHANGE_SORTING_ITEM = 'bus/CHANGE_SORTING_ITEM'
const UPDATE_PRICE_FILTER = 'bus/UPDATE_PRICE_FILTER'
const APPLY_FILTER = 'bus/APPLY_FILTER'
const RESET_PRICE_FILTER = 'bus/RESET_PRICE_FILTER'
const RESET_FACILITIES_FILTER = 'bus/RESET_FACILITIES_FILTER'
const CHANGE_FACILITIES_ITEM = 'bus/CHANGE_FACILITIES_ITEM'
const RESET_FACILITIES = 'bus/RESET_FACILITIES'
const CHANGE_BUS_TYPE = 'bus/CHANGE_BUS_TYPE'
const CHANGE_BUS_SERVICE = 'bus/CHANGE_BUS_SERVICE'
const OPEN_DISCARD_OUTBOUND = 'bus/OPEN_DISCARD_OUTBOUND'

export {
  SAVE_BUS_TIMES,
  APPLY_SORTING,
  CHANGE_SELECTED_FILTER,
  CHANGE_SORTING_ITEM,
  UPDATE_PRICE_FILTER,
  APPLY_FILTER,
  RESET_PRICE_FILTER,
  RESET_FACILITIES_FILTER,
  CHANGE_FACILITIES_ITEM,
  RESET_FACILITIES,
  CHANGE_BUS_TYPE,
  CHANGE_BUS_SERVICE,
  NO_BUS_TIMES,
  OPEN_DISCARD_OUTBOUND

}
