export const SET_CUSTOMER_DETAILS = 'user/SET_CUSTOMER_DETAILS';
export const SET_VOUCHER_CODE = 'user/SET_VOUCHER_CODE';
export const TOGGLE_USE_WALLET_BALANCE = 'user/TOGGLE_USE_WALLET_BALANCE';
export const RESET_USER_CHECKOUT_STATE = 'user/RESET_USER_CHECKOUT_STATE';

export const APPLY_VOUCHER_PENDING = 'user/APPLY_VOUCHER_PENDING';
export const APPLY_VOUCHER_SUCCESS = 'user/APPLY_VOUCHER_SUCCESS';
export const APPLY_VOUCHER_FAILURE = 'user/APPLY_VOUCHER_FAILURE';

export const GET_WALLET_BALANCE_SUCCESS = 'user/GET_WALLET_BALANCE_SUCCESS';
