const BUS_FETCHING = 'bus/BUS_FETCHING'
const SELECTED_BUS = 'bus/SELECTED_BUS'
const BUS_FAILURE = 'bus/BUS_FAILURE'
const BUS_SERVICES_SUCCESS = 'bus/BUS_SERVICES_SUCCESS'
const BUS_SERVICES_RECENT_SEARCH = 'bus/BUS_SERVICES_RECENT_SEARCH'
const SAVE_BUS_OBJ = 'bus/SAVE_BUS_OBJ'
const UPDATE_BUS_OBJ = 'bus/UPDATE_BUS_OBJ'
const SAVE_OUTBOUND_OBJ = 'bus/SAVE_OUTBOUND_OBJ'
const RESET_OUTBOUND_OBJ = 'bus/RESET_OUTBOUND_OBJ'
const SAVE_INBOUND_OBJ = 'bus/SAVE_INBOUND_OBJ'
const RESET_INBOUND_OBJ = 'bus/RESET_INBOUND_OBJ'
const CHNAGE_IS_OUTBOUND = 'bus/CHNAGE_IS_OUTBOUND'
const SAVE_OUTBOUND_SEATINFO_DETAIL = 'bus/SAVE_OUTBOUND_SEATINFO_DETAIL'
const SAVE_INBOUND_SEATINFO_DETAIL = 'bus/SAVE_INBOUND_SEATINFO_DETAIL'
const SAVE_USER_DEATIL = 'bus/SAVE_USER_DEATIL'
const RESET_ALL_STATE = 'bus/RESET_ALL_STATE'
const UPDATE_SEAT_COUNT = 'bus/UPDATE_SEAT_COUNT'
const SELECTED_SEATS = 'bus/SELECTED_SEATS'
const SAVE_BUS_AND_TERMINAL_IMAGES = 'bus/SAVE_BUS_AND_TERMINAL_IMAGES'
const PROGRESS_COUNTER = 'bus/PROGRESS_COUNTER'
const ACTIVE_BUNDLES = 'bus/ACTIVE_BUNDLES'
const SAVE_BUS_SETTING = 'bus/SAVE_BUS_SETTING'
const IS_SHOW_BUNDLE_SHEET = 'bus/IS_SHOW_BUNDLE_SHEET'

export {
  IS_SHOW_BUNDLE_SHEET,
  BUS_FETCHING,
  SELECTED_BUS,
  BUS_FAILURE,
  BUS_SERVICES_SUCCESS,
  BUS_SERVICES_RECENT_SEARCH,
  SAVE_BUS_OBJ,
  UPDATE_BUS_OBJ,
  SAVE_OUTBOUND_OBJ,
  RESET_OUTBOUND_OBJ,
  SAVE_INBOUND_OBJ,
  RESET_INBOUND_OBJ,
  CHNAGE_IS_OUTBOUND,
  SAVE_OUTBOUND_SEATINFO_DETAIL,
  PROGRESS_COUNTER,
  SAVE_INBOUND_SEATINFO_DETAIL,
  SAVE_USER_DEATIL,
  RESET_ALL_STATE,
  UPDATE_SEAT_COUNT,
  SELECTED_SEATS,
  SAVE_BUS_AND_TERMINAL_IMAGES,
  ACTIVE_BUNDLES,
  SAVE_BUS_SETTING
}
