const CHANGE_NICK_NAME = 'CHANGE_NICK_NAME'
const CHANGE_NICK_NAME_ERROR = 'CHANGE_NICK_NAME_ERROR'
const CHANGE_FIRSTNAME = 'CHANGE_FIRSTNAME'
const CHANGE_FIRSTNAME_ERROR = 'CHANGE_FIRSTNAME_ERROR'
const CHANGE_LASTNAME = 'CHANGE_LASTNAME'
const CHANGE_LASTNAME_ERROR = 'CHANGE_LASTNAME_ERROR'
const CHANGE_PHONENO = 'CHANGE_PHONENO'
const CHANGE_PHONENO_ERROR = 'CHANGE_PHONENO_ERROR'
const CHANGE_EMAIL = 'CHANGE_EMAIL'
const CHANGE_EMAIL_ERROR = 'CHANGE_EMAIL_ERROR'
const ONERROR = 'ONERROR'
const CHANGE_PASSPORT_ISSUANCE = 'CHANGE_PASSPORT_ISSUANCE'
const ONCHNAGECNIC = 'ONCHNAGECNIC'
const ON_CHANGE_ID_TYPE = 'ON_CHANGE_ID_TYPE'
const ONCHANGECOUNTRY = 'ONCHANGECOUNTRY'
const ONCHANGEPASSPORT = 'ONCHANGEPASSPORT'
const CHANGE_DOB = 'CHANGE_DOB'
const CHNANGE_ISSUE_COUNTRY = 'CHNANGE_ISSUE_COUNTRY'
const CHANGE_PASSPORT_EXPIRY = 'CHANGE_PASSPORT_EXPIRY'
const CHANGE_GENDER = 'CHANGE_GENDER'

export {
  CHANGE_NICK_NAME,
  CHANGE_NICK_NAME_ERROR,
  CHANGE_FIRSTNAME,
  CHANGE_FIRSTNAME_ERROR,
  CHANGE_LASTNAME,
  CHANGE_LASTNAME_ERROR,
  CHANGE_PHONENO,
  CHANGE_PHONENO_ERROR,
  CHANGE_EMAIL,
  CHANGE_EMAIL_ERROR,
  ON_CHANGE_ID_TYPE,
  ONERROR,
  ONCHNAGECNIC,
  ONCHANGECOUNTRY,
  CHANGE_DOB,
  CHANGE_PASSPORT_ISSUANCE,
  CHNANGE_ISSUE_COUNTRY,
  CHANGE_PASSPORT_EXPIRY,
  ONCHANGEPASSPORT,
  CHANGE_GENDER,
}
