/**
 * created by Inspire UI @author(dang@inspireui.com)
 * @format
 */

const SET_DASHBOARD_DATA = "home/SET_DASHBOARD_DATA";
const SAVE_DISCOUNT_CAMPAIGNS = "home/SAVE_DISCOUNT_CAMPAIGNS";
const SAVE_VOUCHER_SETTING = "home/SAVE_VOUCHER_SETTING";
const ONPENDIG = "home/ONPENDIG";
const SAVE_SHOWCASE = "home/SAVE_SHOWCASE";
const SAVE_TIME_STAMP_PUSHBANNER = "home/SAVE_TIME_STAMP_PUSHBANNER";
const IS_LOADING = "home/IS_LOADING";
const ONSUCCESS = "home/ONSUCCESS";
const ONFAILURE = "home/ONFAILURE";
const UPDATE_APP = "home/UPDATE_APP";
const SAVE_LOGISTIC_CITIES = "home/SAVE_LOGISTIC_CITIES";
const SAVE_EXPERIENCE_CITY = "home/SAVE_EXPERIENCE_CITY";
const SAVE_HOTEL_CITY = "home/SAVE_HOTEL_CITY";
const SAVE_BUS_CITIES = "home/SAVE_BUS_CITIES";
const SAVE_BUS_SERVICES = "home/SAVE_BUS_SERVICES";
const SAVE_PAYMENT_METHODS = "home/SAVE_PAYMENT_METHODS";
const SAVE_MOVIES = "home/SAVE_MOVIES";
const SAVE_EVENTS = "home/SAVE_EVENTS";
const SAVE_VOUCHER = "home/SAVE_VOUCHER";
const BANNER_COUNT = "home/BANNER_COUNT";
const RESET_TIME_STAMP = "home/RESET_TIME_STAMP";
const UPDATE_STORY = "home/UPDATE_STORY";
const SESSION_KEY = "home/SESSION_KEY";
const LOCATION_DATA = "home/LOCATION_DATA";

const SAVE_VOTING_DATA = "home/SAVE_VOTING_DATA";
const HOME_ICONS = "home/HOME_ICONS";
const SAVE_USER_TIER = "settings/SAVE_USER_TIER";

export {
  SET_DASHBOARD_DATA,
  ONPENDIG,
  ONSUCCESS,
  ONFAILURE,
  UPDATE_APP,
  SAVE_VOTING_DATA,
  BANNER_COUNT,
  SAVE_LOGISTIC_CITIES,
  HOME_ICONS,
  SAVE_HOTEL_CITY,
  SAVE_BUS_CITIES,
  SAVE_BUS_SERVICES,
  SAVE_PAYMENT_METHODS,
  SAVE_MOVIES,
  SAVE_VOUCHER_SETTING,
  SAVE_EVENTS,
  SAVE_VOUCHER,
  LOCATION_DATA,
  SAVE_SHOWCASE,
  SAVE_TIME_STAMP_PUSHBANNER,
  IS_LOADING,
  SAVE_DISCOUNT_CAMPAIGNS,
  SAVE_EXPERIENCE_CITY,
  SESSION_KEY,
  RESET_TIME_STAMP,
  UPDATE_STORY,
  SAVE_USER_TIER
};
