const SAVE_AIRELINE_OBJECT = 'airline/SAVE_AIRLINE_OBJECT'
const SAVE_TOKEN = 'airline/SAVE_TOKEN'
const SAVE_HOME_DATA = 'airline/SAVE_HOME_DATA'
const SAVE_POPULAR_AIRPORTS = 'airline/SAVE_POPULAR_AIRPORTS'
const SAVE_AIRPORTS = 'airline/SAVE_AIRPORTS'
const SAVE_CALENGER_FARES = 'airline/SAVE_CALENGER_FARES'
const SAVE_SEARCH_RESULT = 'airline/SAVE_SEARCH_RESULT'
const SAVE_PROGRESS_COUNT = 'airline/SAVE_PROGRESS_COUNT'
const SAVE_AIRLINE_FILTERS = 'airline/SAVE_AIRLINE_FILTERS'
const APPLY_FITLER = 'airline/APPLY_FITLER'
const APPLY_SORTING = 'airline/APPLY_SORTING'
const COPY_SEARCH_RESULT = 'airline/COPY_SEARCH_RESULT'
const SAVE_AIRLINE_SETTING = 'airline/SAVE_AIRLINE_SETTING'
const SAVE_BAGGAGE_INFO = 'airline/SAVE_BAGGAGE_INFO'
const SAVE_MEAL_INFO = 'airline/SAVE_MEAL_INFO'
const SAVE_SEAT_INFO = 'airline/SAVE_SEAT_INFO'
const SAVE_SSR_INFO= 'airline/SAVE_SSR_INFO'
const IS_FETCHING = 'airline/IS_FETCHING'
const FLIGHT_DETAIL = 'airline/FLIGHT_DETAIL'
const SAVE_RECENT_AIRLINE_SEARCH = 'airline/SAVE_RECENT_AIRLINE_SEARCH'
const SAVE_MODIFY_CHANGES = 'airline/SAVE_MODIFY_CHANGES'

export {
    SAVE_AIRELINE_OBJECT,
    IS_FETCHING,
    SAVE_HOME_DATA,
    FLIGHT_DETAIL,
    SAVE_TOKEN,
    APPLY_FITLER,
    SAVE_AIRLINE_SETTING,
    SAVE_AIRPORTS,
    SAVE_POPULAR_AIRPORTS,
    APPLY_SORTING,
    SAVE_PROGRESS_COUNT,
    COPY_SEARCH_RESULT,
    SAVE_SEARCH_RESULT,
    SAVE_BAGGAGE_INFO,
    SAVE_MEAL_INFO,
    SAVE_CALENGER_FARES,
    SAVE_SEAT_INFO,
    SAVE_SSR_INFO,
    SAVE_AIRLINE_FILTERS,
  SAVE_MODIFY_CHANGES,
  SAVE_RECENT_AIRLINE_SEARCH
}
