export const SET_SEARCH_QUERY = 'restaurant/SET_SEARCH_QUERY';
export const CLEAR_SELECTED_RESTAURANT = 'restaurant/CLEAR_SELECTED_RESTAURANT';

export const SEARCH_RESTAURANTS_PENDING = 'restaurant/SEARCH_RESTAURANTS_PENDING';
export const SEARCH_RESTAURANTS_SUCCESS = 'restaurant/SEARCH_RESTAURANTS_SUCCESS';
export const SEARCH_RESTAURANTS_FAILURE = 'restaurant/SEARCH_RESTAURANTS_FAILURE';

export const GET_HOME_LISTINGS_PENDING = 'restaurant/GET_HOME_LISTINGS_PENDING';
export const GET_HOME_LISTINGS_SUCCESS = 'restaurant/GET_HOME_LISTINGS_SUCCESS';
export const GET_HOME_LISTINGS_FAILURE = 'restaurant/GET_HOME_LISTINGS_FAILURE';

export const GET_RESTAURANT_DETAILS_PENDING = 'restaurant/GET_RESTAURANT_DETAILS_PENDING';
export const GET_RESTAURANT_DETAILS_SUCCESS = 'restaurant/GET_RESTAURANT_DETAILS_SUCCESS';
export const GET_RESTAURANT_DETAILS_FAILURE = 'restaurant/GET_RESTAURANT_DETAILS_FAILURE';
