/**
 * created by Inspire UI @author(dang@inspireui.com)
 * @format
 */
const INITIAL_APP = 'app/INITIAL'
const FINISH_INTRO = 'app/FINISH_INTRO'
const DEFAULT_LANGUAGE = {
    lang: 'en',
    rtl: false
}
const SAVE_AIRPOTS_CITIES = 'home/SAVE_AIRPOTS_CITIES'
/**
 * notification
 */
const NOTIFICATION_ENABLE = 'app/notification/ENABLE'
const NOTIFICATION_DISABLE = 'app/notification/DISABLE'
const NOTIFICATION_TOGGLE = 'app/notification/TOGGLE'
const SAVE_PUSH_NOTIFICATION = 'app/notification/SAVE_PUSH_NOTIFICATION'
const SAVE_OTP_METHODS = 'app/SAVE_OTP_METHODS'

const SAVE_FCM_TOKEN = 'app/SAVE_FCM_TOKEN'
const BANNER_COUNT = 'app/BANNER_COUNT'
const SAVE_DEVICE_INFO = 'app/SAVE_DEVICE_INFO'
const PN_COUNT = 'app/PN_COUNT'
const RATING_DONE = 'app/RATING_DONE'
const START_FETCHING = 'app/START_FETCHING'
const STOP_FETCHING = 'app/STOP_FETCHING'


const CHANGE_CURRENCEY = 'app/CHANGE_CURRENCEY'

const DIALOG_OPENING = 'app/DIALOG_OPENING'
const IS_FIRST_LOGIN = 'app/IS_FIRST_LOGIN'
const DIALOG_CLOSING = 'app/DIALOG_CLOSING'
const ADD_REFER_ID = 'app/ADD_REFER_ID'
const ADD_USER_TYPE = 'app/ADD_USER_TYPE'
const APP_SESSION_COUNT = 'app/APP_SESSION_COUNT'
const PERMISSION_INTERVAL = 'app/PERMISSION_INTERVAL'

const PROBLEMS_LIST = 'app/PROBLEMS_LIST'

/**
 * language
 */
const LANGUAGE_CHANGE = 'app/language/CHANGE'
const CHANGE_THEME = 'app/CHANGE_THEME'
const RTL_CHANGE = 'app/rtl/CHANGE'

/**
 * netinfo
 */
const UPDATE_CONNECTION_STATUS = 'app/network/UPDATE_STATUS'

/**
 * toast
 */
const ADD_TOAST = 'app/toast/ADD'
const REMOVE_TOAST = 'app/toast/REMOVE'
const ADD_NOTIFICATION = 'app/notification/ADD'
const REMOVE_NOTIFCATION = 'app/notification/REMOVE'

/**
 * sidemenu
 */
const SIDEMENU_OPEN = 'app/sidemenu/OPEN'
const SIDEMENU_CLOSE = 'app/sidemenu/CLOSE'
const SIDEMENU_TOGGLE = 'app/sidemenu/TOGGLE'


const APP_UPDATE_DIALOG_SHOW = 'app/APP_UPDATE_DIALOG_SHOW'
const UPDATION_DETAIL = 'app/UPDATION_DETAIL'
const UPDATE_PREVIOUS_LANGUAGE = 'app/UPDATE_PREVIOUS_LANGUAGE'


const SAVE_AIRLINE_INFO_DIALOG = 'app/SAVE_AIRLINE_INFO_DIALOG'

export {
    INITIAL_APP,
    FINISH_INTRO,
    NOTIFICATION_ENABLE,
    NOTIFICATION_DISABLE,
    NOTIFICATION_TOGGLE,
    LANGUAGE_CHANGE,
  UPDATE_PREVIOUS_LANGUAGE,
    ADD_NOTIFICATION,
  SAVE_AIRLINE_INFO_DIALOG,
    REMOVE_NOTIFCATION,
    RTL_CHANGE,
    IS_FIRST_LOGIN,
    SAVE_DEVICE_INFO,
    UPDATE_CONNECTION_STATUS,
    SIDEMENU_OPEN,
    SIDEMENU_CLOSE,
    SIDEMENU_TOGGLE,
    ADD_TOAST,
    REMOVE_TOAST,
    SAVE_FCM_TOKEN,
    SAVE_PUSH_NOTIFICATION,
    PN_COUNT,
    CHANGE_CURRENCEY,
    DIALOG_OPENING,
    BANNER_COUNT,
    DIALOG_CLOSING,
    ADD_USER_TYPE,
    RATING_DONE,
    START_FETCHING,
    APP_SESSION_COUNT,
    PERMISSION_INTERVAL,
    STOP_FETCHING,
    ADD_REFER_ID,
    DEFAULT_LANGUAGE,
    CHANGE_THEME,
    SAVE_AIRPOTS_CITIES,
  SAVE_OTP_METHODS,
    PROBLEMS_LIST,
    APP_UPDATE_DIALOG_SHOW,
    UPDATION_DETAIL
}
