export const SET_SELECTED_DATE = 'booking/SET_SELECTED_DATE';
export const SET_SELECTED_TIME_SLOT = 'booking/SET_SELECTED_TIME_SLOT';
export const SET_GUEST_COUNT = 'booking/SET_GUEST_COUNT';
export const SET_SPECIAL_REQUESTS = 'booking/SET_SPECIAL_REQUESTS';
export const RESET_BOOKING = 'booking/RESET_BOOKING';

export const CREATE_BOOKING_PENDING = 'booking/CREATE_BOOKING_PENDING';
export const CREATE_BOOKING_SUCCESS = 'booking/CREATE_BOOKING_SUCCESS';
export const CREATE_BOOKING_FAILURE = 'booking/CREATE_BOOKING_FAILURE';

export const GET_POLICY_PENDING = 'booking/GET_POLICY_PENDING';
export const GET_POLICY_SUCCESS = 'booking/GET_POLICY_SUCCESS';
export const GET_POLICY_FAILURE = 'booking/GET_POLICY_FAILURE';

export const GET_AVAILABILITY_PENDING = 'booking/GET_AVAILABILITY_PENDING';
export const GET_AVAILABILITY_SUCCESS = 'booking/GET_AVAILABILITY_SUCCESS';
export const GET_AVAILABILITY_FAILURE = 'booking/GET_AVAILABILITY_FAILURE';
